### ISSUE TITLE
Alphabetical NAVIGATION System (GLOSSARY)

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#46]
Any chance to make a navigational system, alphabetical, so when you look through glossary you can jump to certain letters.

Some fixed header like, A,B,C,D,E etc.
![screen shot 2014-10-24 at 1 21 42 pm](https://cloud.githubusercontent.com/assets/9045718/4775782/83121ae4-5bbb-11e4-93ee-6bce5acd925f.png)

**Comment by caseyg** [comment]
Instead of adding navigation for an insanely long list which looked kind of dry and didn't take advantage of interactivity, I completely changed the layout of this to use hovers. On mobile will probably revert to a straight list or tap to expand definition. What do you think @troykreiner?

![screen shot 2015-04-03 at 12 12 27 am](https://cloud.githubusercontent.com/assets/462020/6977962/b45b3c58-d996-11e4-9e25-98526f3c6488.png)

You can play with it here: http://freecooperunion.org/disorientation/glossary/

If this looks good/better I'll close this issue. Also happy to make changes/improvements.
