### ISSUE TITLE
Navigation function on Opening page

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#48]
Love the opening page its really coming together.
Since it takes up the full broswer I can see some people maybe not scrolling.

If you click the collage could the navigation send/glide you down to the disOrientation section that explains the project, if you click that part (black background) it will send/glide you down to the chapter section...

It will add more assistance to the navigation.

![screen shot 2014-10-24 at 1 25 15 pm](https://cloud.githubusercontent.com/assets/9045718/4775858/1a7f3574-5bbc-11e4-82c2-1a00a8b990a1.png)

**Comment by caseyg** [comment]
Yeah for sure.

Part of me wants to make every collage element its own transparent image and have them move in a kind of parallaxy way, or pop in and out one at a time, or keep switching which ones are visible in an animation. Watcha think?

I was also imagining a more dynamic index, where rather than lists of content, there was a grid of collage images and titles, e.g.

![img_9769](https://cloud.githubusercontent.com/assets/462020/4781379/fe64285a-5c9b-11e4-90f5-ced0fec819e9.JPG)

**Comment by troykreiner** [comment]
I realllly like the second idea, I think that makes way more sense and easier to naviagte, the list is a little over whelming and takes dedication. Its functional for now but yeah 2nd idea is rad.

The parallax stuff could be interesting, im not a huge fan of cosmetic parallax stuff unless it doesnt take a lot of effort on the development side and is subtle... but if you have a specific idea i say go for  it!

**Comment by caseyg** [comment]
So I still hate the list that we left off with months ago:

![screen shot 2015-04-02 at 10 44 47 pm](https://cloud.githubusercontent.com/assets/462020/6977391/34ae4cfe-d98a-11e4-92a8-c7789830d09c.png)

But I am having a hard time coming up with a non-corporate looking implementation of a boxy layout:

![screen shot 2015-04-02 at 10 44 17 pm](https://cloud.githubusercontent.com/assets/462020/6977397/4535d2c2-d98a-11e4-8bb2-10a4f6218365.png)

Doesn't that look stupid, like it's trying to sell you something and the images don't really convey any information, and the red feels wrong?

But at least not as crappy as the list...

Maybe use B&W collage elements instead of the faded red images?

Would be happy for you to take a pass or give input, @troykreiner.

![screen shot 2015-04-02 at 11 06 43 pm](https://cloud.githubusercontent.com/assets/462020/6977513/f6cf02ae-d98c-11e4-96f2-b614440edf88.png)

**Comment by troykreiner** [comment]
I just had an idea. when you first come to the site, the landing collage should work as a navigational experience too because all the images are paired with articles/sections, and if you hover over certain images it reveals a hover dialogue (like the glossary) and can shoot you over to the associated article/essay... just the intiial DIVE in. but you can then go to the top navigational menu after that...

does that make sense???

**Comment by caseyg** [comment]
That would be cool, my hesitations are:
1. Mystery meat hover navigation is annoying https://en.wikipedia.org/wiki/Mystery_meat_navigation
2. It's a pain to build: positioning a bunch of collaged elements as individual links means converting positions to pixels, and then if anything changes the whole thing needs to be recollaged and reconverted into pixel alignments, and then if you consider responsiveness & flexible screen sizes & browser quirks, it's a positioning nightmare.
3. Reading in sequence kinda matters for the Lowdown section

I do think we need something more exciting and useful than three mindnumbing lists, but less corporate than my Spotify-esque mocks above lol.

Should also think about how to make the resources more attractive: basically there's a map, a timeline, a glossary, a spectrum. Crazy interfaces. So some way to highlight that. Screenshots? Icons?

**Comment by caseyg** [comment]
Took another stab at the grid layout, whaddya think @troykreiner? Also live to play with at http://freecooperunion.org

![screen shot 2015-04-12 at 4 51 32 pm](https://cloud.githubusercontent.com/assets/462020/7107471/57cae9c0-e134-11e4-8294-0c2f80187c2c.png)
